---
# role: ansible-role-qemu
# file: .travis.yml

language: python

os: linux
dist: focal

branches:
  only:
    - main

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install ansible yamllint ansible-lint

script:
  - ansible-lint
